CREATE TABLE bird_search (
  ID SERIAL PRIMARY KEY,
  SP_ID INT REFERENCES bird_description,
  SEX CHAR DEFAULT 'G',
  BEAK_TYPE INT,
  BODY_TYPE INT,
  TAIL_TYPE INT,
  LEG_TYPE INT
);

INSERT INTO bird_search (SP_ID, SEX, BEAK_TYPE, BODY_TYPE, TAIL_TYPE, LEG_TYPE)
VALUES (1,'M', 1, 1, 2, 3);

INSERT INTO bird_search (SP_ID, SEX, BEAK_TYPE, BODY_TYPE, TAIL_TYPE, LEG_TYPE)
VALUES (2, 'G', 1, 1, 3, 3);

INSERT INTO bird_search (SP_ID, SEX, BEAK_TYPE, BODY_TYPE, TAIL_TYPE, LEG_TYPE)
    VALUES (3, 'G', 1, 4, 1, 3);