CREATE TABLE bird_search (
  ID              SERIAL PRIMARY KEY,
  SP_ID  INT NOT NULL,
  SEX VARCHAR(2),
  BEAK_SHAPE INT,
  BEAK_LEN INT,
  BEAK_SIZE INT,
  BODY_TYPE INT,
  BODY_SIZE INT,
  TAIL_SHAPE INT,
  TAIL_LEN INT,
  TAIL_SIZE INT,
  LEGS_SHAPE INT,
  
  
);